name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-92.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  # Para fazer a entrada do telefone
  mask_text_input_formatter: ^2.4.0
  flutter_animate: ^4.1.1+1
  dotted_decoration: ^2.0.0
  pie_chart: ^5.3.2
  syncfusion_flutter_gauges: ^21.2.4
  web_socket_channel: ^2.4.0
  rive: ^0.10.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
   - family: Inter
     fonts:
        - asset: Assets/Fonts/Inter-Medium.ttf
        - asset: Assets/Fonts/Inter-Bold.ttf
          weight: 700
        - asset: Assets/Fonts/Inter-Light.ttf
          weight: 300

  assets:
    - Assets/Images/icon.png
    - Assets/Images/cloud.png
    - Assets/Images/viasaticon.jpeg
    - Assets/Images/application.png
    - Assets/Images/check-list.png
    - Assets/Images/neural.png
    - Assets/Images/report.png
    - Assets/Images/speedometer.png
    - Assets/Images/warning.png
    - Assets/Images/chatbot.png
    - Assets/Images/check.png
    - Assets/Animations/log_in_animation.riv
    - Assets/Animations/sign_up_animation.riv
